name: Build

on:
  push:
    tags:
      - "v*"

env:
  BUILD_TYPE: Release

jobs:
  windows-build:
    runs-on: windows-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B build

      - name: Build
        run: cmake --build build --config ${{env.BUILD_TYPE}}

      - name: Upload compressor
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          asset_name: EternalTextureCompressor-Windows.exe
          file: ${{github.workspace}}/build/Release/EternalTextureCompressor.exe
          tag: ${{github.ref}}

      - name: Upload decompressor
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          asset_name: EternalTextureDecompressor-Windows.exe
          file: ${{github.workspace}}/build/Release/EternalTextureDecompressor.exe
          tag: ${{github.ref}}

  linux-build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B build

      - name: Build
        run: cmake --build build --config ${{env.BUILD_TYPE}}

      - name: Rename and strip binaries
        run: |
          mv build/EternalTextureCompressor EternalTextureCompressor-Linux
          mv build/EternalTextureDecompressor EternalTextureDecompressor-Linux
          strip EternalTextureCompressor-Linux
          strip EternalTextureDecompressor-Linux

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{secrets.GITHUB_TOKEN}}"
          prerelease: false
          files: |
            ${{github.workspace}}/EternalTextureCompressor-Linux
            ${{github.workspace}}/EternalTextureDecompressor-Linux
